language: node_js

node_js:
  - 12.16.1

cache:
  directories:
    - 'node_modules'

notifications:
  email:
    on_success: never

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run report
